version: "3.8"

services:
  web:
    image: nginx:1.25-alpine
    container_name: nginx-custom-config-web
    ports:
      - "8081:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
