services:
  web:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./custom.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
