version: "3.8"

services:
  web:
    image: nginx:1.25-alpine
    container_name: nginx-basic-web
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
