version: "3"
services:
  web:
    image: nginx:alpine
    ports:
      - "8443:443"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./ssl.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    restart: unless-stopped
