version: "3"
services:
  web:
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
